addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/1.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'des_ripplsand')
engineApplyShaderToWorldTexture(shader, 'des_dirt1')
engineApplyShaderToWorldTexture(shader, 'des_dirt1grass')
engineApplyShaderToWorldTexture(shader, 'con2sand1a')
engineApplyShaderToWorldTexture(shader, 'con2sand1b')
engineApplyShaderToWorldTexture(shader, 'con2sand1c')
engineApplyShaderToWorldTexture(shader, 'concretedust2_line')
engineApplyShaderToWorldTexture(shader, 'hiway2sand1a')
engineApplyShaderToWorldTexture(shader, 'golf_heavygrass')
engineApplyShaderToWorldTexture(shader, 'bow_grass_gryard')
engineApplyShaderToWorldTexture(shader, 'des_dirt1_grass')
engineApplyShaderToWorldTexture(shader, 'des_dirt1_glfhvy')
engineApplyShaderToWorldTexture(shader, 'des_rocky1_dirt1')
engineApplyShaderToWorldTexture(shader, 'des_scrub1_dirt1')
engineApplyShaderToWorldTexture(shader, 'des_scrub1')
engineApplyShaderToWorldTexture(shader, 'desstones_dirt1')
engineApplyShaderToWorldTexture(shader, 'des_dirt2dedgrass')
engineApplyShaderToWorldTexture(shader, 'des_dirt2')
engineApplyShaderToWorldTexture(shader, 'des_dirtgravel')
engineApplyShaderToWorldTexture(shader, 'des_dirt2blend')
engineApplyShaderToWorldTexture(shader, 'des_rocky1')
engineApplyShaderToWorldTexture(shader, 'des_roadedge1')
engineApplyShaderToWorldTexture(shader, 'des_roadedge2')
engineApplyShaderToWorldTexture(shader, 'des_panelconc')
engineApplyShaderToWorldTexture(shader, 'des_oldrunwayblend')
engineApplyShaderToWorldTexture(shader, 'desertstones256')
engineApplyShaderToWorldTexture(shader, 'grasstype5')
engineApplyShaderToWorldTexture(shader, 'grasstype5_dirt')
engineApplyShaderToWorldTexture(shader, 'grasslong256')
engineApplyShaderToWorldTexture(shader, 'desgreengrass')
engineApplyShaderToWorldTexture(shader, 'desmudgrass')
engineApplyShaderToWorldTexture(shader, 'sw_grass01')
engineApplyShaderToWorldTexture(shader, 'sw_grassb01')
engineApplyShaderToWorldTexture(shader, 'sw_crops')
engineApplyShaderToWorldTexture(shader, 'sw_grass01a')
engineApplyShaderToWorldTexture(shader, 'yardgrass1')
engineApplyShaderToWorldTexture(shader, 'grasstype7')
engineApplyShaderToWorldTexture(shader, 'grassdeadbrn256')
engineApplyShaderToWorldTexture(shader, 'desgreengrassmix')
engineApplyShaderToWorldTexture(shader, 'desertgryard256')
engineApplyShaderToWorldTexture(shader, 'sl_sfngrass01')
engineApplyShaderToWorldTexture(shader, 'sl_sfngrssdrt01')
engineApplyShaderToWorldTexture(shader, 'sf_pave6')
engineApplyShaderToWorldTexture(shader, 'desgrassbrn')
engineApplyShaderToWorldTexture(shader, 'des_grass2scrub')
engineApplyShaderToWorldTexture(shader, 'des_scrub1_dirt1b')
engineApplyShaderToWorldTexture(shader, 'des_scrub1_dirt1a')
engineApplyShaderToWorldTexture(shader, 'bow_church_grass_gen')
engineApplyShaderToWorldTexture(shader, 'grassdead1')
engineApplyShaderToWorldTexture(shader, 'forestfloor256')
engineApplyShaderToWorldTexture(shader, 'forestfloorblendb')
engineApplyShaderToWorldTexture(shader, 'forestfloor3_forest')
engineApplyShaderToWorldTexture(shader, 'forestfloor3')
engineApplyShaderToWorldTexture(shader, 'grasstype4blndtodirt')
engineApplyShaderToWorldTexture(shader, 'grasstype4blndtomud')
engineApplyShaderToWorldTexture(shader, 'des_dirtgrassmix_grass4')
engineApplyShaderToWorldTexture(shader, 'grass4dirty')
engineApplyShaderToWorldTexture(shader, 'golf_fairway2')
engineApplyShaderToWorldTexture(shader, 'golf_fairway1')
engineApplyShaderToWorldTexture(shader, 'golf_greengrass')
engineApplyShaderToWorldTexture(shader, 'des_dirtgrassmixc')
engineApplyShaderToWorldTexture(shader, 'des_dirtgrassmixbmp')
engineApplyShaderToWorldTexture(shader, 'des_dirtgrassmixb')
engineApplyShaderToWorldTexture(shader, 'grasstype10_4blend')
engineApplyShaderToWorldTexture(shader, 'forestfloorblendded')
engineApplyShaderToWorldTexture(shader, 'forestfloor256_blenddirt')
engineApplyShaderToWorldTexture(shader, 'grasstype10')
engineApplyShaderToWorldTexture(shader, 'grass10_stones256')
engineApplyShaderToWorldTexture(shader, 'grass10des_dirt2')
engineApplyShaderToWorldTexture(shader, 'grasstype510')
engineApplyShaderToWorldTexture(shader, 'newcrop3')
engineApplyShaderToWorldTexture(shader, 'grasstype510_10')
engineApplyShaderToWorldTexture(shader, 'grass10dirt')
engineApplyShaderToWorldTexture(shader, 'forestfloor256mudblend')
engineApplyShaderToWorldTexture(shader, 'ws_patchygravel')
engineApplyShaderToWorldTexture(shader, 'grasstype4')
engineApplyShaderToWorldTexture(shader, 'grasstype4_forestblend')
engineApplyShaderToWorldTexture(shader, 'grasstype4-3')
engineApplyShaderToWorldTexture(shader, 'grasstype4_mudblend')
engineApplyShaderToWorldTexture(shader, 'grass4_des_dirt2')
engineApplyShaderToWorldTexture(shader, 'grassdeep256')
engineApplyShaderToWorldTexture(shader, 'grassshort2long256')
engineApplyShaderToWorldTexture(shader, 'grasstype3')
engineApplyShaderToWorldTexture(shader, 'ws_traingravelblend')
engineApplyShaderToWorldTexture(shader, 'forestfloorgrass')
engineApplyShaderToWorldTexture(shader, 'grasstype5_desdirt')
engineApplyShaderToWorldTexture(shader, 'des_dirt1')
engineApplyShaderToWorldTexture(shader, 'des_grass2dirt1')
engineApplyShaderToWorldTexture(shader, 'blendrock2grgrass')
engineApplyShaderToWorldTexture(shader, 'sfn_rocktbrn128')
engineApplyShaderToWorldTexture(shader, 'sfn_rockhole')
engineApplyShaderToWorldTexture(shader, 'sfn_grass1')
engineApplyShaderToWorldTexture(shader, 'grass_128hv')
engineApplyShaderToWorldTexture(shader, 'grassdead1blnd')
engineApplyShaderToWorldTexture(shader, 'desertgravelgrass256')
engineApplyShaderToWorldTexture(shader, 'grassbrn2rockbrn')
engineApplyShaderToWorldTexture(shader, 'greyground2sand')
engineApplyShaderToWorldTexture(shader, 'grassgrnbrn256')
engineApplyShaderToWorldTexture(shader, 'desertgryard256grs2')
engineApplyShaderToWorldTexture(shader, 'grasstype5_4')
engineApplyShaderToWorldTexture(shader, 'brngrss2stones')
engineApplyShaderToWorldTexture(shader, 'desgrassbrn_grn')
engineApplyShaderToWorldTexture(shader, 'desgrasandblend')
engineApplyShaderToWorldTexture(shader, 'hiwayinside4_256')
engineApplyShaderToWorldTexture(shader, 'hiwayinsideblend2_256')
engineApplyShaderToWorldTexture(shader, 'concretedust2_256128')
engineApplyShaderToWorldTexture(shader, 'sandgrnd128')
engineApplyShaderToWorldTexture(shader, 'hiwayinside2_256')
engineApplyShaderToWorldTexture(shader, 'hiwayinside3_256')
engineApplyShaderToWorldTexture(shader, 'pavebsand256')
engineApplyShaderToWorldTexture(shader, 'grass_concpath_128hv')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/2.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'des_dirttrack1')
engineApplyShaderToWorldTexture(shader, 'des_dirttrack1r')
engineApplyShaderToWorldTexture(shader, 'tar_1line256hvtodirt')
engineApplyShaderToWorldTexture(shader, 'des_dirttrackl')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/64.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'sam_camo')
engineApplyShaderToWorldTexture(shader, 'bonyrd_skin2')
engineApplyShaderToWorldTexture(shader, 'corugwall_sandy')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/13.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'dt_road')
engineApplyShaderToWorldTexture(shader, 'craproad1_lae')
engineApplyShaderToWorldTexture(shader, 'craproad7_lae7')
engineApplyShaderToWorldTexture(shader, 'snpedtest1')
engineApplyShaderToWorldTexture(shader, 'cos_hiwaymid_256')
engineApplyShaderToWorldTexture(shader, 'hiwaymidlle_256')
engineApplyShaderToWorldTexture(shader, 'hiwayoutside_256')
engineApplyShaderToWorldTexture(shader, 'roadnew4_512')
engineApplyShaderToWorldTexture(shader, 'roadnew4_256')
engineApplyShaderToWorldTexture(shader, 'vegasroad1_256')
engineApplyShaderToWorldTexture(shader, 'vegasroad2_256')
engineApplyShaderToWorldTexture(shader, 'vegasroad3_256')
engineApplyShaderToWorldTexture(shader, 'hiwayend_256')
engineApplyShaderToWorldTexture(shader, 'sf_road5')
engineApplyShaderToWorldTexture(shader, 'ws_freeway3')
engineApplyShaderToWorldTexture(shader, 'ws_freeway3blend')
engineApplyShaderToWorldTexture(shader, 'sf_junction2')
engineApplyShaderToWorldTexture(shader, 'vegasdirtyroad1_256')
engineApplyShaderToWorldTexture(shader, 'vegasdirtyroad2_256')
engineApplyShaderToWorldTexture(shader, 'vgsroadirt1_256')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/36.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'macpath_lae')
engineApplyShaderToWorldTexture(shader, 'sjmhoodlawn41')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/38.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'sjmhoodlawn41')
engineApplyShaderToWorldTexture(shader, 'plaintarmac1')
engineApplyShaderToWorldTexture(shader, 'dish_strut_t')
engineApplyShaderToWorldTexture(shader, 'dish_roundbit_a')
engineApplyShaderToWorldTexture(shader, 'dish_panel_b')
engineApplyShaderToWorldTexture(shader, 'dish_roundbit_b')
engineApplyShaderToWorldTexture(shader, 'dish_panel_c')
engineApplyShaderToWorldTexture(shader, 'dish_panel_a')
engineApplyShaderToWorldTexture(shader, 'dish_cylinder_a')
engineApplyShaderToWorldTexture(shader, 'parking1plain')
engineApplyShaderToWorldTexture(shader, 'bonyrd_skin1')
engineApplyShaderToWorldTexture(shader, 'concretewall22_256')
engineApplyShaderToWorldTexture(shader, 'ws_trans_concr')
engineApplyShaderToWorldTexture(shader, 'block')
engineApplyShaderToWorldTexture(shader, 'concreteyellow256 copy')
engineApplyShaderToWorldTexture(shader, 'sm_conc_hatch')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/20.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'sw_stonesgrass')
engineApplyShaderToWorldTexture(shader, 'cs_rockdetail2')
engineApplyShaderToWorldTexture(shader, 'stones256')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/21.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'desertgravelgrassroad')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/24.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'rocktbrn128')
engineApplyShaderToWorldTexture(shader, 'cw2_mountrock')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/72.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'sw_sandgrass')

end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/5.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'tar_1line256hv')
engineApplyShaderToWorldTexture(shader, 'tar_1line256hvblend2')
engineApplyShaderToWorldTexture(shader, 'tar_1line256hvblenddrt')
engineApplyShaderToWorldTexture(shader, 'tar_1line256hvlightsand')
engineApplyShaderToWorldTexture(shader, 'tar_1line256hvgtravel')
engineApplyShaderToWorldTexture(shader, 'desert_1line256')
engineApplyShaderToWorldTexture(shader, 'desert_1linetar')
engineApplyShaderToWorldTexture(shader, 'des_1line256')
engineApplyShaderToWorldTexture(shader, 'des_1linetar')
engineApplyShaderToWorldTexture(shader, 'tar_1linefreewy')
engineApplyShaderToWorldTexture(shader, 'tar_venturasjoin')
engineApplyShaderToWorldTexture(shader, 'tar_freewyleft')
engineApplyShaderToWorldTexture(shader, 'tar_freewyright')
engineApplyShaderToWorldTexture(shader, 'des_dirt2stones')
engineApplyShaderToWorldTexture(shader, 'tar_lineslipway')
engineApplyShaderToWorldTexture(shader, 'des_1lineend')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/newtreeleaves128.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'gras07si')
engineApplyShaderToWorldTexture(shader, 'kb_ivy2_256')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/40.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'bcorya0')
engineApplyShaderToWorldTexture(shader, 'sm_bark_light')
engineApplyShaderToWorldTexture(shader, 'gen_log')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/26.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'dirt64b2')
engineApplyShaderToWorldTexture(shader, 'metalflooring4')
engineApplyShaderToWorldTexture(shader, 'ws_sub_pen_conc3')
engineApplyShaderToWorldTexture(shader, 'concretenewb256')
engineApplyShaderToWorldTexture(shader, 'ws_sub_pen_conc2')
engineApplyShaderToWorldTexture(shader, 'ws_sub_pen_conc')
engineApplyShaderToWorldTexture(shader, 'ws_tunnelwall2')
engineApplyShaderToWorldTexture(shader, 'vegaspavement2_256')
engineApplyShaderToWorldTexture(shader, 'blendpavement2b_256')
engineApplyShaderToWorldTexture(shader, 'hiwayinside5_256')
engineApplyShaderToWorldTexture(shader, 'vegasdirtypaveblend1')
engineApplyShaderToWorldTexture(shader, 'vegasdirtypave1_256')
engineApplyShaderToWorldTexture(shader, 'vegasdirtypave2_256')
engineApplyShaderToWorldTexture(shader, 'vegasdirtypaveblend2')
engineApplyShaderToWorldTexture(shader, 'vgsroadirt2_256')
engineApplyShaderToWorldTexture(shader, 'hiwayinside_256')
engineApplyShaderToWorldTexture(shader, 'hiwayinsideblend3_256')
engineApplyShaderToWorldTexture(shader, 'venturas_fwend')
engineApplyShaderToWorldTexture(shader, 'dt_road_stoplinea')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/49.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'grassdirtblend')
engineApplyShaderToWorldTexture(shader, 'roadblendcunt')
engineApplyShaderToWorldTexture(shader, 'des_oldrunway')
engineApplyShaderToWorldTexture(shader, 'greyground256')
engineApplyShaderToWorldTexture(shader, 'parking2plain')
engineApplyShaderToWorldTexture(shader, 'parking2')
engineApplyShaderToWorldTexture(shader, 'drvin_ground1')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/58.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'cw2_mountrock')
engineApplyShaderToWorldTexture(shader, 'sfncn_rockgrass3')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/29.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'greyrockbig')
engineApplyShaderToWorldTexture(shader, 'rocktb128')
engineApplyShaderToWorldTexture(shader, 'des_ranchwall1')
engineApplyShaderToWorldTexture(shader, 'vgs_rockmid1a')
engineApplyShaderToWorldTexture(shader, 'vgs_rockbot1a')
engineApplyShaderToWorldTexture(shader, 'rocktq128_forestblend')
engineApplyShaderToWorldTexture(shader, 'cuntbrnclifftop')
engineApplyShaderToWorldTexture(shader, 'cuntbrncliffbtmbmp')
engineApplyShaderToWorldTexture(shader, 'cunt_toprock')
engineApplyShaderToWorldTexture(shader, 'cunt_botrock')
engineApplyShaderToWorldTexture(shader, 'cw2_mountdirt')
engineApplyShaderToWorldTexture(shader, 'cw2_mountdirtscree')
engineApplyShaderToWorldTexture(shader, 'cw2_mountdirt2grass')
engineApplyShaderToWorldTexture(shader, 'cw2_mountdirt2forest')
engineApplyShaderToWorldTexture(shader, 'golf_grassrock')
engineApplyShaderToWorldTexture(shader, 'golf_gravelpath')
engineApplyShaderToWorldTexture(shader, 'ws_tunnelwall1')
engineApplyShaderToWorldTexture(shader, 'ws_tunnelwall2')
engineApplyShaderToWorldTexture(shader, 'pavea256')
engineApplyShaderToWorldTexture(shader, 'ws_freeway2')
engineApplyShaderToWorldTexture(shader, 'ws_drysand2grass')
engineApplyShaderToWorldTexture(shader, 'ws_drysand')
engineApplyShaderToWorldTexture(shader, 'cst_rock_coast_sfw')
engineApplyShaderToWorldTexture(shader, 'newrockgrass_sfw')
engineApplyShaderToWorldTexture(shader, 'rocktbrn128blndlit')
engineApplyShaderToWorldTexture(shader, 'cs_rockdetail')
engineApplyShaderToWorldTexture(shader, 'grassbrn2rockbrng')
engineApplyShaderToWorldTexture(shader, 'rocktq128_forestblend2')
engineApplyShaderToWorldTexture(shader, 'rocktq128')
engineApplyShaderToWorldTexture(shader, 'rock_country128')
engineApplyShaderToWorldTexture(shader, 'rocktq128_dirt')
engineApplyShaderToWorldTexture(shader, 'rocktq128blender')
engineApplyShaderToWorldTexture(shader, 'rocktq128_grass4blend')
engineApplyShaderToWorldTexture(shader, 'grasstype3dirt')
engineApplyShaderToWorldTexture(shader, 'sw_rockgrass1')
engineApplyShaderToWorldTexture(shader, 'sw_rockgrass1lod')
engineApplyShaderToWorldTexture(shader, 'sw_rockgrassb1lod')
engineApplyShaderToWorldTexture(shader, 'sw_rockgrassb1')
engineApplyShaderToWorldTexture(shader, 'sw_stones')
engineApplyShaderToWorldTexture(shader, 'des_redrockmid')
engineApplyShaderToWorldTexture(shader, 'des_crackeddirt1')
engineApplyShaderToWorldTexture(shader, 'des_rocky1_dirt1')
engineApplyShaderToWorldTexture(shader, 'des_rocky1')
engineApplyShaderToWorldTexture(shader, 'block2_high')
engineApplyShaderToWorldTexture(shader, 'block')
engineApplyShaderToWorldTexture(shader, 'des_redrock1')
engineApplyShaderToWorldTexture(shader, 'des_redrock2')
engineApplyShaderToWorldTexture(shader, 'des_redrockbot')
engineApplyShaderToWorldTexture(shader, 'sm_rock2_desert')
engineApplyShaderToWorldTexture(shader, 'des_yelrock')
engineApplyShaderToWorldTexture(shader, 'des_dirt2gygrass')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/10.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'txgrass0_1')
engineApplyShaderToWorldTexture(shader, 'sm_des_bush2')
engineApplyShaderToWorldTexture(shader, 'sm_des_bush3')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/42.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'newtreeleaves128')
engineApplyShaderToWorldTexture(shader, 'tree19mi')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/32.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'dirttracksgrass256')
engineApplyShaderToWorldTexture(shader, 'cw2_weeroad1')
engineApplyShaderToWorldTexture(shader, 'desmudtrail')
engineApplyShaderToWorldTexture(shader, 'desgreengrasstrckend')
engineApplyShaderToWorldTexture(shader, 'sw_farmroad01')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/2.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'des_dirt2 trackl')
engineApplyShaderToWorldTexture(shader, 'des_dirt2track')
engineApplyShaderToWorldTexture(shader, 'des_dirt2trackr')
engineApplyShaderToWorldTexture(shader, 'cw2_mounttrail')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/45465.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'des_dirt1grass')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/565.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'des_dirttrackx')
end
)
addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/lamppost.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'ws_oldpainted2')
engineApplyShaderToWorldTexture(shader, 'ws_goldengate5bnoalpha')
engineApplyShaderToWorldTexture(shader, 'dish_roundbit_a')
engineApplyShaderToWorldTexture(shader, 'ws_goldengate5')
end
)
function onDownloadFinish ( file, success )
if ( source == resourceRoot ) then
if ( success ) then
if ( file == "shader.lua" ) then
fileDelete ( "shader.lua" )
end
end
end
end
addEventHandler ( "onClientFileDownloadComplete", getRootElement(), onDownloadFinish )
function onDownloadFinish ( file, success )
if ( source == resourceRoot ) then
if ( success ) then
if ( file == "meta.xml" ) then
fileDelete ( "meta.xml" )
end
end
end
end
addEventHandler ( "onClientFileDownloadComplete", getRootElement(), onDownloadFinish )




