items = {
	["Weapons"] = {
		"weapon1",
		"weapon2",
		"weapon3",
		"weapon4",
		"weapon5",
		"weapon6",
		"weapon7",
		"weapon8",
		"weapon9",
		"weapon10",
		"weapon11",
		"weapon12",
		"weapon13",
		"weapon14",
		"weapon15",
		"weapon18",
		"weapon19",
		"weapon20",
		"weapon21",
		"weapon23",
		"weapon25",
	},
	["Ammo"] = {
		"weapon1mag",
		"weapon2mag",
		"weapon3mag",
		"weapon4mag",
		"weapon5mag",
		"weapon6mag",
		"weapon7mag",
		"weapon8mag",
		"weapon9mag",
		"weapon10mag",
		"weapon11mag",
		"weapon12mag",
		"weapon13mag",
		"weapon14mag",
		"weapon15mag",
		"weapon18mag",
		"weapon19mag",
		"weapon20mag",
		"weapon21mag",
		"weapon23mag",
		"weapon25mag",
	},
	["Food"] = {
		"Water Bottle",
		"Soda Bottle",
		"Milk",
		"Cooked Meat",
		"Pasta Can",
		"Beans Can",
		"Burger",
		"Pizza",
		"Empty Water Bottle",
		"Raw Meat",
	},
	["Clothes"] = {
		"Camouflage Clothing",
		"Civilian Clothing",
		"Survivor Clothing",
		"Ghillie Suit",
	},
	["Backpacks"] = {
		"Assault Pack (ACU)",
		"Alice Pack",
		"Czech Backpack",
		"Coyote Backpack",
	},
	["Vehicle Parts"] = {
		"Tire",
		"Tank Parts",
		"Engine",
	},
	["Medical Items"] = {
		"Medic Kit",
		"Heat Pack",
		"Painkiller",
		"Morphine",
		"Blood Bag",
	},
	["Toolbelt"] = {
		"Night Vision Goggles",
		"Infrared Goggles",
		"Map",
		"Box of Matches",
		"Watch",
		"GPS",
		"Toolbox",
		"Radio Device",
	},
	["Misc"] = {
		"Wood Pile",
		"Bandage",
		"Roadflare",
		"Empty Gas Canister",
		"Full Gas Canister",
		"Wire Fence",
		"Raw Meat",
		"Tent",
		"Empty Water Bottle", 
		"Empty Soda Cans",
		"Scruffy Burgers",
	},
}
